version: '3.4'

services:

  client:
    container_name: web
    image: helloarchy/projects/web/projects
    build:
      context: .
      dockerfile: web/projects/dockerfile
    ports:
      - 3000:3000
    networks:
      - frontend

  gateway:
    container_name: gateway
    image: helloarchy/projects/gateway
    build:
      context: .
      dockerfile: gateway/projects.gateway/dockerfile
    ports:
      - 5001:443
      - 5000:80
    networks:
      - frontend
      - backend
    links:
      - project-svc
    depends_on:
      - project-svc

  identity:
    container_name: identity
    image: helloarchy/projects/identity
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 4000:80
    networks:
      - frontend
      - backend

  project-svc:
    container_name: service.project.api
    image: helloarchy/projects/services/project.api
    build:
      context: Services/Project/Project.API
      dockerfile: dockerfile
    ports:
      - 6000:80
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
