version: '3.4'

services:

  client:
    container_name: web
    image: helloarchy/projects/web/projects
    build:
      context: ./web/projects/
      dockerfile: Dockerfile
    environment:
      GATEWAY: "${GATEWAY}"
    ports:
      - 3000:3000
    networks:
      - frontend

  gateway:
    container_name: gateway
    image: helloarchy/projects/gateway
    build:
      context: ./gateway/projects.gateway
      dockerfile: Dockerfile
    ports:
      - 5001:443
      - 5000:80
    networks:
      - frontend
      - backend
    links:
      - project-svc
    depends_on:
      - project-svc

  identity:
    container_name: identity
    image: helloarchy/projects/identity
    build:
      context: ./identity/identity
      dockerfile: Dockerfile
    environment:
      IDENTITY_DB_PASSWORD: "${IDENTITY_DB_PASSWORD}"
      IDENTITY_DB_SERVER: "${IDENTITY_DB_SERVER}"
      IDENTITY_DB_NAME: "${IDENTITY_DB_NAME}"
      IDENTITY_DB_USER: "${IDENTITY_DB_USER}"
    ports:
      - 4000:80
      - 4001:443
    networks:
      - frontend
      - backend

  identity-db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "${IDENTITY_DB_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "4101:1433"
    networks:
      - backend

  project-svc:
    container_name: service.project
    image: helloarchy/projects/services/project
    build:
      context: ./services/project/project.api
      dockerfile: Dockerfile
    environment:
      PROJECT_DB_PASSWORD: "${PROJECT_DB_PASSWORD}"
      PROJECT_DB_SERVER: "${PROJECT_DB_SERVER}"
      PROJECT_DB_NAME: "${PROJECT_DB_NAME}"
      PROJECT_DB_USER: "${PROJECT_DB_USER}"
    ports:
      - 6000:80
    networks:
      - backend
    depends_on:
      - project-db

  project-db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "${PROJECT_DB_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "6101:1433"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
